module.exports = [
  {
    id: "action-resume-upload",
    title: "Upload & Scan Resume ATS",
    description: "Submit your engineering resume PDF to calculate search keyword matches and ATS scores.",
    type: "Resume",
    category: "General",
    prerequisites: [],
    estimatedTime: "10 mins",
    expectedImpact: 2,
    scoreReward: 2,
    xpReward: 50,
    confidence: 90,
    reason: "Optimizing resume alignment passes initial ATS candidate screens in 100% of target vacancies."
  },
  {
    id: "action-resume-keywords",
    title: "Optimize Resume Keywords",
    description: "Align your profile description with Backend/Frontend keywords generated by the scanner.",
    type: "Resume",
    category: "General",
    prerequisites: ["action-resume-upload"],
    estimatedTime: "30 mins",
    expectedImpact: 3,
    scoreReward: 3,
    xpReward: 100,
    confidence: 92,
    reason: "ATS algorithms filter applications using strict keyword matches (Node.js, React, AWS)."
  }
];
